CREATE TABLE profesion (
	codigo tinyint(3) unsigned primary key,
	descripcion varchar(40) not null,
	status tinyint(1) unsigned not null default 1,
	cod_usr_reg int unsigned not null,
	fec_reg timestamp not null default current_timestamp,
	cod_usr_mod int unsigned not null,
	fec_mod timestamp not null DEFAULT 0,
  foreign key (cod_usr_reg)
    references usuario(codigo)
    on update cascade
    on delete restrict,
  foreign key (cod_usr_mod)
    references usuario(codigo)
    on update cascade
    on delete restrict
)
CHARACTER SET utf8
COLLATE utf8_general_ci;

INSERT INTO profesion
(codigo, descripcion, cod_usr_reg, cod_usr_mod, fec_mod)
values
(1, 'ABOGADO', 1, 1, current_timestamp),
(2, 'ACTOR, ACTRIZ', 1, 1, current_timestamp),
(3, 'ADMINISTRADOR', 1, 1, current_timestamp),
(4, 'AGENTE VIAJERO', 1, 1, current_timestamp),
(5, 'AGRICULTOR', 1, 1, current_timestamp),
(6, 'ALBAÑIL', 1, 1, current_timestamp),
(7, 'AMA DE CASA', 1, 1, current_timestamp),
(8, 'ANALISTA', 1, 1, current_timestamp),
(9, 'ARQUITECTO', 1, 1, current_timestamp),
(10, 'ATLETA', 1, 1, current_timestamp),
(11, 'AUDITOR', 1, 1, current_timestamp),
(12, 'AUXILIAR DE LABORATORIO', 1, 1, current_timestamp),
(13, 'AUXILIAR DE ENFERMERIA', 1, 1, current_timestamp),
(14, 'AUXILIAR DE FARMACIA', 1, 1, current_timestamp),
(15, 'AZAFATA', 1, 1, current_timestamp),
(16, 'BAILARIN', 1, 1, current_timestamp),
(17, 'BARBERO', 1, 1, current_timestamp),
(18, 'BARMAN', 1, 1, current_timestamp),
(19, 'BOMBERO', 1, 1, current_timestamp),
(20, 'BOTANICO', 1, 1, current_timestamp),
(21, 'CAJERO', 1, 1, current_timestamp),
(22, 'CAMARERO, CAMARERA', 1, 1, current_timestamp),
(23, 'CAMAROGRAFO', 1, 1, current_timestamp),
(24, 'CAMILLERO', 1, 1, current_timestamp),
(25, 'CANTANTE', 1, 1, current_timestamp),
(26, 'CARNICERO', 1, 1, current_timestamp),
(27, 'CARPINTERO', 1, 1, current_timestamp),
(28, 'CARTERO', 1, 1, current_timestamp),
(29, 'CERRAJERO', 1, 1, current_timestamp),
(30, 'CIENTIFICO', 1, 1, current_timestamp),
(31, 'COMERCIANTE', 1, 1, current_timestamp),
(32, 'COMPOSITOR', 1, 1, current_timestamp),
(33, 'COCINERO', 1, 1, current_timestamp),
(34, 'CHOFER', 1, 1, current_timestamp),
(35, 'CONTADOR', 1, 1, current_timestamp),
(36, 'CONTRATISTA DE OBRA', 1, 1, current_timestamp),
(37, 'COSTURERA', 1, 1, current_timestamp),
(38, 'DECORADOR', 1, 1, current_timestamp),
(39, 'DENTISTA', 1, 1, current_timestamp),
(40, 'DIRECTOR DE ESCUELA', 1, 1, current_timestamp),
(41, 'DIRECTOR DE ORQUESTA', 1, 1, current_timestamp),
(42, 'DISEÑADOR GRAFICO', 1, 1, current_timestamp),
(43, 'DOCENTE', 1, 1, current_timestamp),
(44, 'ECONOMISTA', 1, 1, current_timestamp),
(45, 'EDITOR', 1, 1, current_timestamp),
(46, 'ELECTRICISTA', 1, 1, current_timestamp),
(47, 'ENFERMERO/A', 1, 1, current_timestamp),
(48, 'ESCOLTA', 1, 1, current_timestamp),
(49, 'ESCRITOR', 1, 1, current_timestamp),
(50, 'ESCULTOR', 1, 1, current_timestamp),
(51, 'FARMACEUTICO', 1, 1, current_timestamp),
(52, 'FISICO', 1, 1, current_timestamp),
(53, 'FLORISTA', 1, 1, current_timestamp),
(54, 'FOTOGRAFO', 1, 1, current_timestamp),
(55, 'FRUTERO', 1, 1, current_timestamp),
(56, 'GEOLOGO', 1, 1, current_timestamp),
(57, 'GUARDA-PARQUES', 1, 1, current_timestamp),
(58, 'HERRERO', 1, 1, current_timestamp),
(59, 'INGENIERO', 1, 1, current_timestamp),
(60, 'JARDINERO', 1, 1, current_timestamp),
(61, 'JOYERO', 1, 1, current_timestamp),
(62, 'JUEZ', 1, 1, current_timestamp),
(63, 'LATONERO', 1, 1, current_timestamp),
(64, 'LICENCIADO', 1, 1, current_timestamp),
(65, 'LOCUTOR', 1, 1, current_timestamp),
(66, 'MAQUINISTA', 1, 1, current_timestamp),
(67, 'MATEMATICO', 1, 1, current_timestamp),
(68, 'MECANICO', 1, 1, current_timestamp),
(69, 'MEDICO', 1, 1, current_timestamp),
(70, 'MEDICO VETERINARIO', 1, 1, current_timestamp),
(71, 'MILITAR', 1, 1, current_timestamp),
(72, 'MODELO', 1, 1, current_timestamp),
(73, 'MODISTA', 1, 1, current_timestamp),
(74, 'MUSICO', 1, 1, current_timestamp),
(75, 'NIÑERA', 1, 1, current_timestamp),
(76, 'NUTRICIONISTA', 1, 1, current_timestamp),
(77, 'OBRERO', 1, 1, current_timestamp),
(78, 'OFICIAL DE POLICIA', 1, 1, current_timestamp),
(79, 'OFICIAL DE SEGURIDAD', 1, 1, current_timestamp),
(80, 'PANADERO', 1, 1, current_timestamp),
(81, 'PASTELERO', 1, 1, current_timestamp),
(82, 'PEDIATRA', 1, 1, current_timestamp),
(83, 'PELUQUERO', 1, 1, current_timestamp),
(84, 'PERIODISTA', 1, 1, current_timestamp),
(85, 'PERITO MERCANTIL', 1, 1, current_timestamp),
(86, 'PESCADOR', 1, 1, current_timestamp),
(87, 'PILOTO', 1, 1, current_timestamp),
(88, 'PLOMERO', 1, 1, current_timestamp),
(89, 'PINTOR', 1, 1, current_timestamp),
(90, 'POLITICO', 1, 1, current_timestamp),
(91, 'PROFESOR UNIVERSITARIO', 1, 1, current_timestamp),
(92, 'PROGRAMADOR', 1, 1, current_timestamp),
(93, 'PSICOLOGO', 1, 1, current_timestamp),
(94, 'PSICOTERAPEUTA', 1, 1, current_timestamp),
(95, 'PSIQUIATRA', 1, 1, current_timestamp),
(96, 'PUBLICISTA', 1, 1, current_timestamp),
(97, 'QUIMICO', 1, 1, current_timestamp),
(98, 'RADIOLOGO', 1, 1, current_timestamp),
(99, 'RECEPCIONISTA', 1, 1, current_timestamp),
(100, 'SACERDOTE, MONJA', 1, 1, current_timestamp),
(101, 'SASTRE', 1, 1, current_timestamp),
(102, 'SECRETARIO/A', 1, 1, current_timestamp),
(103, 'SIN PROFESION', 1, 1, current_timestamp),
(104, 'SUPERVISOR/A', 1, 1, current_timestamp),
(105, 'TAXISTA', 1, 1, current_timestamp),
(106, 'TEOLOGO', 1, 1, current_timestamp),
(107, 'TRADUCTOR DE IDIOMA', 1, 1, current_timestamp),
(108, 'ZAPATERO', 1, 1, current_timestamp),
(255,'OTRO', 1, 1, current_timestamp);
